apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-push
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: tekton-learning-workspace
      description: The workspace where the cloned repository will be stored.
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
  steps:
    - name: push
      image: alpine/git
      script: |
        #!/bin/sh
        export HOME=/workspace/tekton-learning-workspace
        git config --global --add safe.directory /workspace/tekton-learning-workspace
        git config --global credential.helper store
        git config --global user.email "swapnil0115@gmail.com"
        git config --global user.name "swapnil0115"
        echo "https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com" > ~/.git-credentials
        
        cd /workspace/tekton-learning-workspace

        echo "Directories in /:"
        ls -la

        echo "Directories in /workspace:"
        ls -la /workspace

        echo "Directories in /workspace/tekton-learning-workspace:"
        ls -la /workspace/tekton-learning-workspace
        
        git add .
        git commit -m "Automated commit from Tekton pipeline"
        git push $(params.repo-url) $(params.branch)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
