apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: tekton-learning-workspace
      description: The workspace where the cloned repository will be stored.
  params:
    - name: url
      type: string
    - name: revision
      type: string
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        mkdir -p /workspace/output
        cd /workspace/output
        git clone $(params.url) --branch $(params.revision) /workspace/output
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
