apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-push
  namespace: tekton-pipelines
spec:
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
  steps:
    - name: push
      image: alpine/git
      script: |
        #!/bin/sh
        git config --global credential.helper store
        echo "https://swapnil0115_token@github.com" > ~/.git-credentials
        cd /workspace/output
        git add .
        git commit -m "Automated commit from Tekton pipeline"
        git push $(params.repo-url) $(params.branch)