apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-push
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: tekton-learning-workspace
      description: The workspace where the cloned repository will be stored.
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
  steps:
    - name: push
      image: alpine/git
      script: |
        #!/bin/sh
        git config --global credential.helper store
        echo "https://swapnil0115_token@github.com" > ~/.git-credentials
        cd /workspace
        git add .
        git commit -m "Automated commit from Tekton pipeline"
        git push $(params.repo-url) $(params.branch)
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
