apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: tekton-learning-workspace
      description: The workspace where the cloned repository will be stored.
  steps:
    - name: test
      image: python:3.10
      script: |
        #!/bin/sh
        cd /workspace/output
        python -m unittest discover
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
