apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
  namespace: spare-machine
spec:
  steps:
    - name: test
      image: python:3.10
      script: |
        #!/bin/sh
        cd /workspace/output
        python -m unittest discover
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
