apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
spec:
  steps:
    - name: test
      image: python:3.10
      script: |
        #!/bin/sh
        cd /workspace/output
        python -m unittest discover