apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: push-to-github
  namespace: tekton-pipelines
spec:
  params:
    - name: url
      type: string
      description: The URL of the Git repository to clone.
    - name: revision
      type: string
      description: The branch or commit to checkout.
    - name: sha
      type: string
      description: The sha of the commit to set the status for.
    - name: action
      type: string
      description: The action that triggered the pipeline (e.g., opened, synchronize).
    - name: pull_request_id
      type: string
      description: The ID of the pull request.
    - name: branch
      type: string
      description: The branch to push changes to.
    - name: REPO_FULL_NAME
      type: string
      description: The full name of the GitHub repository (e.g., user/repo).
    - name: GITHUB_HOST_URL
      type: string
      description: The GitHub host URL (default is api.github.com).
      default: api.github.com
  tasks:
    - name: set-status-start
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.REPO_FULL_NAME)
        - name: sha
          value: "$(params.sha)"
        - name: DESCRIPTION
          value: "Build has started"
        - name: STATE
          value: pending
        - name: TARGET_URL
          value: https://9568-2401-4900-1cb9-3984-9912-5a47-467e-9b73.ngrok-free.app
        - name: API_PATH_PREFIX
          value: ""
        - name: GITHUB_TOKEN_SECRET_KEY
          value: password
        - name: GITHUB_HOST_URL
          value: $(params.GITHUB_HOST_URL)
  
    - name: clone-repo
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      runAfter:
        - set-status-start
      workspaces:
        - name: tekton-learning-workspace

    - name: run-tests
      taskRef:
        name: run-tests
        kind: Task
      runAfter:
        - clone-repo
      workspaces:
        - name: tekton-learning-workspace

    - name: push-to-github
      taskRef:
        name: git-push
        kind: Task
      runAfter:
        - run-tests
      params:
        - name: repo-url
          value: $(params.url)
        - name: branch
          value: $(params.branch)
      workspaces:
        - name: tekton-learning-workspace

  finally:
    - name: set-status-success
      when:
        - input: $(tasks.run-tests.status)
          operator: in
          values: ["Succeeded"]
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.REPO_FULL_NAME)
        - name: sha
          value: "$(params.sha)"
        - name: DESCRIPTION
          value: "Build has succeeded"
        - name: STATE
          value: success
        - name: TARGET_URL
          value: https://9568-2401-4900-1cb9-3984-9912-5a47-467e-9b73.ngrok-free.app
        - name: GITHUB_TOKEN_SECRET_KEY
          value: password
        - name: API_PATH_PREFIX
          value: ""
        - name: GITHUB_HOST_URL
          value: $(params.GITHUB_HOST_URL)
    - name: set-status-failure
      when:
        - input: $(tasks.run-tests.status)
          operator: in
          values: ["Failed"]
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.REPO_FULL_NAME)
        - name: sha
          value: "$(params.sha)"
        - name: DESCRIPTION
          value: "Build has failed"
        - name: STATE
          value: failure
        - name: TARGET_URL
          value: https://9568-2401-4900-1cb9-3984-9912-5a47-467e-9b73.ngrok-free.app
        - name: GITHUB_TOKEN_SECRET_KEY
          value: password
        - name: API_PATH_PREFIX
          value: ""
        - name: GITHUB_HOST_URL
          value: $(params.GITHUB_HOST_URL)

  workspaces:
    - name: tekton-learning-workspace
