apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: push-to-github-run
spec:
  pipelineRef:
    name: push-to-github
  workspaces:
    - name: tekton-learning-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
