apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: push-to-github
  namespace: tekton-pipelines
spec:
  params:
    - name: url
      type: string
      description: The URL of the Git repository to clone.
    - name: revision
      type: string
      description: The branch or commit to checkout.
    - name: sha
      type: string
      description: The SHA of the commit to set the status for.
    - name: action
      type: string
      description: The action that triggered the pipeline (e.g., opened, synchronize).
    - name: pull_request_id
      type: string
      description: The ID of the pull request.
    - name: branch
      type: string
      description: The branch to push changes to.
  tasks:
    - name: set-status-start
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.url)
        - name: SHA
          value: "$(params.sha)"
        - name: DESCRIPTION
          value: "Build has started"
        - name: STATE
          value: pending
        - name: TARGET_URL
          value: https://ebc5-2401-4900-1cb9-2330-299b-8aa9-4a71-5f64.ngrok-free.app
      workspaces:
        - name: tekton-learning-workspace

    - name: clone-repo
      taskRef:
        name: git-clone
        kind: Task
      params:
        - name: url
          value: $(params.url)
        - name: revision
          value: $(params.revision)
      runAfter:
        - set-status-start
      workspaces:
        - name: tekton-learning-workspace

    - name: run-tests
      taskRef:
        name: run-tests
        kind: Task
      runAfter:
        - clone-repo
      workspaces:
        - name: tekton-learning-workspace

    - name: push-to-github
      taskRef:
        name: git-push
        kind: Task
      runAfter:
        - run-tests
      params:
        - name: repo-url
          value: $(params.url)
        - name: branch
          value: $(params.branch)
      workspaces:
        - name: tekton-learning-workspace

  finally:
    - name: set-status-success
      when:
        - input: $(tasks.run-tests.status)
          operator: in
          values: ["Succeeded"]
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.url)
        - name: SHA
          value: "$(params.sha)"
        - name: DESCRIPTION
          value: "Build has succeeded"
        - name: STATE
          value: success
        - name: TARGET_URL
          value: https://ebc5-2401-4900-1cb9-2330-299b-8aa9-4a71-5f64.ngrok-free.app
      workspaces:
        - name: tekton-learning-workspace
    
    - name: set-status-failure
      when:
        - input: $(tasks.run-tests.status)
          operator: in
          values: ["Failed"]
      taskRef:
        name: github-set-status
      params:
        - name: REPO_FULL_NAME
          value: $(params.url)
        - name: SHA
          value: "$(params.sha)"
        - name: DESCRIPTION
          value: "Build has failed"
        - name: STATE
          value: failure
        - name: TARGET_URL
          value: https://ebc5-2401-4900-1cb9-2330-299b-8aa9-4a71-5f64.ngrok-free.app
      workspaces:
        - name: tekton-learning-workspace
  
  workspaces:
    - name: tekton-learning-workspace
