apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-rolebinding
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # or a more restrictive role if you prefer
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: tekton-pipelines
