apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline-triggers-admin
  namespace: spare-machine
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: spare-machine
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
