apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: github-listener
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: tekton-learning-workspace
      description: The workspace where the cloned repository will be stored.
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: github-push-binding
      template:
        ref: pipeline-trigger-template
