apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-trigger-template
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
    - name: SHA_code
    - name: gitaction
    - name: GIT_pull_request_id
    - name: GIT_branch
    - name: API_PATH_PREFIX
    - name: GIT_REPO_NAME
    - name: TARGET_URL
    - name: DESCRIPTION
    - name: CONTEXT
    - name: STATE
    - name: AUTH_TYPE
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: push-to-github-$(uid)
        namespace: tekton-pipelines
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: push-to-github
        params:
          - name: url
            value: $(tt.params.gitrepositoryurl)
          - name: revision
            value: $(tt.params.gitrevision)
          - name: sha
            value: $(tt.params.SHA_code)
          - name: action
            value: "$(tt.params.gitaction)"
          - name: pull_request_id
            value: "$(tt.params.GIT_pull_request_id)"
          - name: branch
            value: "$(tt.params.GIT_branch)"
          - name: REPO_FULL_NAME
            value: $(tt.params.GIT_REPO_NAME)
        workspaces:
          - name: git-credentials
            secret:
              secretName: github-secret
          - name: tekton-learning-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
