apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      value: "$(body.pull_request.head.ref)"
    - name: gitrepositoryurl
      value: "$(body.repository.clone_url)"
    - name: SHA_code
      value: "$(body.pull_request.head.sha)"
    - name: gitaction
      value: "$(body.action)"
    - name: GIT_pull_request_id
      value: "$(body.pull_request.id)"
    - name: GIT_branch
      value: "$(body.pull_request.head.ref)"
    - name: GIT_REPO_NAME
      value: $(body.repository.full_name)
