apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: tekton-learning-workspace
      description: The workspace where the cloned repository will be stored.
  params:
    - name: gitrevision
      value: $(body.ref)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
