apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      value: "$(body.pull_request.head.ref)"
    - name: gitrepositoryurl
      value: "$(body.repository.clone_url)"
    - name: sha
      value: "$(body.pull_request.head.sha)"
    - name: action
      value: "$(body.action)"
    - name: pull_request_id
      value: "$(body.pull_request.id)"
    - name: branch
      value: "$(body.pull_request.head.ref)"
    - name: REPO_FULL_NAME
      value: $(body.repository.full_name)
    - name: GITHUB_HOST_URL
      value: "$(body.pull_request.url)"
