apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-trigger-template
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: pipelinerun-build-push-image-$(uid)
        namespace: default
      spec:
        serviceAccountName: pipeline-triggers-admin
        pipelineRef:
          name: push-to-github
        params:
          - name: url
            value: $(tt.params.gitrepositoryurl)
          - name: revision
            value: $(tt.params.gitrevision)
        workspaces:
          - name: tekton-learning-workspace
            emptyDir: {}
        
