apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: pipeline-trigger-template
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
    - name: gitrepositoryurl
    - name: sha
    - name: action
    - name: pull_request_id
    - name: branch
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: push-to-github-$(uid)
        namespace: tekton-pipelines
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: push-to-github
        params:
          - name: url
            value: $(tt.params.gitrepositoryurl)
          - name: revision
            value: $(tt.params.gitrevision)
          - name: sha
            value: $(tt.params.sha)
          - name: action
            value: "$(tt.params.action)"
          - name: pull_request_id
            value: "$(tt.params.pull_request_id)"
          - name: branch
            value: "$(tt.params.branch)"
        workspaces:
          - name: git-credentials
            secret:
              secretName: github-secret
          - name: tekton-learning-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi

#test