apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-push-binding
  namespace: tekton-pipelines
spec:
  params:
    - name: gitrevision
      value: $(body.ref)
    - name: gitrepositoryurl
      value: $(body.repository.clone_url)
    - name: pull_request_id
      value: "$(body.pull_request.id)"
    - name: branch
      value: "$(body.pull_request.head.ref)"
    - name: sha
      value: "$(body.pull_request.head.sha)"